#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
set -o errexit




echo "* Cleaning up."
rm -rf /root/*
sm-prepare-image -y
